### ISSUE TITLE
green pass

### ISSUE THREAD

**Issue by sebbu2** [nipo/tdd#1]
It doesn't work with the french version of the green pass, which is a 2D-DOC.

**Comment by nipo** [comment]
What error do you get out of the library when it tries to parse the document ?

About health certificates as emitted by French CNAM, they provides two different machine-readable codes:

- a datamatrix, which is 2D-Doc, covered by this library, accepted by french authorities,
- a QR-Code, which is European greenpass (aka DCC), not covered by this library, interoperable across all European countries.

French app "Tous Anti Covid Verif" transparently supports both, which leads to a little confusion for some users.

In order to confirm you are actually trying to parse a 2D-Doc, could you double check:

- Code is a datamatrix,
- Textual representation starts with "DC".

If your code is a QR-Code and/or starts with "HC1:", it is an european DCC and is not covered by this library. Other github projects do handle this kind of codes though.

**Comment by sebbu2** [comment]
it starts with :
`QR-Code:https://bonjour.tousanticovid.gouv.fr/app/walletdcc#HC1:`
and contains different data than the european DCC (greenpass).
Both are qrcode.

**Comment by nipo** [comment]
I have a sample of such code here, this is not 2D-Doc.
You see URL fragment starts with DCC marker ("HC1:"), but it is URL-escaped.
Try to extract/unescape the URL, for instance:
```
>>> import urllib.parse
>>> u = urllib.parse.urlparse("https://bonjour.tousanticovid.gouv.fr/app/walletdcc#HC1:...")
>>> urllib.parse.unquote(u.fragment)
HC1:...
>>>
```

Once URL-escaping removed, it should match your the raw DCC payload.
Then pipe this to any project like https://github.com/berdav/greenpass
